[package]
name = "mint-script"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["ms-runtime", "ms-stdlib"]

[dependencies]
ms-runtime = { path = "ms-runtime" }
ms-stdlib = { path = "ms-stdlib" }

[[bin]]
name = "ms"
path = "src/main.rs"
