[package]
name = "mint-script"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[workspace]
members = ["ms-runtime"]

[dependencies]
ms-runtime = { path = "ms-runtime" }

[[bin]]
name = "ms"
path = "src/main.rs"
